### ISSUE TITLE
Slightly different pivot ks when using `LinearPowerModel` models in [km/s] vs [Mpc]

### ISSUE THREAD

**Issue by Chris-Pedersen** [andreufont/LyaCosmoParams#46]
When we set up our simulations, we use a `LinearPowerModel` object created in units of Mpc, with a pivot point of k=0.7 1/Mpc. The sampler is then run using a `LinearPowerModel` in units of km/s and a pivot point of k=0.009 s/km. However the conversion here isn't perfect - using our fiducial h=0.67, the corresponding pivot scale in s/km should be k=0.00913, and the difference results in a ~1.5% difference in the values for Delta2_star when plot the training sims & truth lines on the sampler posteriors. I think this difference is big enough to warrant fixing this, and I can see two obvious ways to do this:

1. Change the default km/s pivot scale to k=0.00913 and rerun our sampler results with this pivot point. This is a less round number and then not the same as MacDonald et al, Chabanier et al and other measurements.
2. Leave the km/s scale as it is but instead change the scale in 1/Mpc, and correct the bookkeeping values in the simulation `.json` files.

What do you think @andreufont  ?

**Comment by andreufont** [comment]
I don't think we need to "fix" this, since it is really not a problem with the setup. Simulation parameters and likelihood parameters are different objects.

If you want to make a plot with both, then you'd have to compute what are the values of Delta_star for each of the simulations, but this could be easily done on the fly, isn't it?

**Comment by Chris-Pedersen** [comment]
Fixed in #59
